### ISSUE TITLE
Why use AVGPool2D in the last layer before Flattening? 

### ISSUE THREAD

**Issue by adhityabagasmiwa** [anhtuan85/Facial-expression-recognition#1]
Hi,

I want to ask about the VGG model, why use **avgpool2d** in the last layer before flattening?

can you explain it?

Thanks.

**Comment by anhtuan85** [comment]
Thank you. This is my mistake. I copied from [here](https://github.com/StephanZheng/neural-fingerprinting/blob/master/models/vgg.py) and not check code. You can delete layer avgpool2d. It is not necessary.

**Comment by adhityabagasmiwa** [comment]
So, if i delete avgpool2d it doesn't affect the accuracy?

**Comment by anhtuan85** [comment]
Yes.

**Comment by adhityabagasmiwa** [comment]
Ok sure, thanks.
