### ISSUE TITLE
Where code to convert RGB to Grayscale Image on Preprocessing? 

### ISSUE THREAD

**Issue by adhityabagasmiwa** [anhtuan85/Facial-expression-recognition#2]
Hi,

I'm confused about converting RGB to Grayscale Image on your code, can you tell me the code to show convert RGB to Grayscale?

Thanks
Best

**Comment by anhtuan85** [comment]
[Here](https://github.com/anhtuan85/Facial-expression-recognition/blob/master/image_demo.py#L58)

**Comment by adhityabagasmiwa** [comment]
This is for a demo, but I asked if the dataset was converted to grayscale before training?

**Comment by anhtuan85** [comment]
No. From each image in data, I create 2-D numpy array (h, w). Then I create tensor shape: (batch_size, 1, h, w) to trainning.

**Comment by adhityabagasmiwa** [comment]
So, if using ToTensor in Pytorch for data image 2-D NumPy array always get 1 channel?

**Comment by anhtuan85** [comment]
Yes.
t = np.ones((49, 49))     #(49, 49)
t = ToTensor()(t)    #(1, 49, 49)

**Comment by adhityabagasmiwa** [comment]
Thanks, i was understood
